package com.bff.wespot.domain.util

object RemoteConfigKey {
    const val MIN_VERSION = "MIN_VERSION"
    const val BASE_URL = "BASE_URL"
    const val MOCK_BASE_URL = "MOCK_BASE_URL"
    const val VOTE_QUESTION_GOOGLE_FORM_URL = "VOTE_QUESTION_GOOGLE_FORM_URL"
    const val WESPOT_KAKAO_CHANNEL_URL = "WESPOT_KAKAO_CHANNEL_URL"
    const val WESPOT_INSTAGRAM_URL = "WESPOT_INSTAGRAM_URL"
    const val USER_OPINION_GOOGLE_FORM_URL = "USER_OPINION_GOOGLE_FORM_URL"
    const val RESEARCH_PARTICIPATION_GOOGLE_FORM_URL = "RESEARCH_PARTICIPATION_GOOGLE_FORM_URL"
    const val WESPOT_MAKERS_URL = "WESPOT_MAKERS_URL"
    const val PROFILE_CHANGE_GOOGLE_FORM_URL = "PROFILE_CHANGE_GOOGLE_FORM_URL"
    const val PRIVACY_POLICY_URL = "PRIVACY_POLICY_URL"
    const val PLAY_STORE_URL = "PLAY_STORE_URL"
    const val TERMS_OF_SERVICE_URL = "TERMS_OF_SERVICE_URL"
    const val SCHOOL_FORM = "SCHOOL_FORM"
    const val MARKETING_SERVICE_TERM = "MARKETING_SERVICE_TERM"
    const val MESSAGE_RECEIVE_TIME = "MESSAGE_RECEIVE_TIME"
    const val MESSAGE_START_TIME = "MESSAGE_START_TIME"
}
